CARD_TYPE_DIGIMON = 1
CARD_TYPE_OPTION = 2
CARD_TYPE_TAMER = 3
CARD_TYPE_DIGIEGG = 4
CARD_TYPE = [
    CARD_TYPE_DIGIMON,
    CARD_TYPE_OPTION,
    CARD_TYPE_TAMER,
    CARD_TYPE_DIGIEGG
]

RARITY_COMMON = 1
RARITY = [
    RARITY_COMMON
]

DIGIMON_COLOR_BLACK = 1
DIGIMON_COLOR_BLUE = 2
DIGIMON_COLOR_COLORLESS = 3
DIGIMON_COLOR_GREEN = 4
DIGIMON_COLOR_PURPLE = 5
DIGIMON_COLOR_RED = 6
DIGIMON_COLOR_WHITE = 7
DIGIMON_COLOR_YELLOW = 8
DIGIMON_COLOR  = [
    DIGIMON_COLOR_BLACK,
    DIGIMON_COLOR_BLUE,
    DIGIMON_COLOR_COLORLESS,
    DIGIMON_COLOR_GREEN,
    DIGIMON_COLOR_PURPLE,
    DIGIMON_COLOR_RED,
    DIGIMON_COLOR_WHITE,
    DIGIMON_COLOR_YELLOW
]

STAGE_DIGITAMA = 1
STAGE_BABY = 2
STAGE_BABY_II = 3
STAGE_ROOKIE = 4
STAGE_ADULT = 5
STAGE_CHAMPION = 6
STAGE_ULTIMATE = 7
STAGE_ARMOR = 8
STAGE_CROSS = 9
STAGE_MEGA = 10
STAGE = [
    STAGE_DIGITAMA,
    STAGE_BABY,
    STAGE_BABY_II,
    STAGE_ROOKIE,
    STAGE_ADULT,
    STAGE_CHAMPION,
    STAGE_ULTIMATE,
    STAGE_ARMOR,
    STAGE_CROSS,
    STAGE_MEGA
]

ATTRIBUTE_VACINNE = 1
ATTRIBUTE = [
    ATTRIBUTE_VACINNE
]

DIGIMON_TYPE_REPTILE = 1
DIGIMON_TYPE = [
    DIGIMON_TYPE_REPTILE
]

PLAYMATE_UNLOCATED = 0
PLAYMATE_DEEP_OCEAN = 1
PLAYMATE_SECURITY_AREA = 2
PLAYMATE_BREEDENG_AREA = 3
PLAYMATE_DARK_AREA = 4
PLAYMATE_HAND = 5
PLAYMATE = [
    PLAYMATE_UNLOCATED,
    PLAYMATE_DEEP_OCEAN,
    PLAYMATE_SECURITY_AREA,
    PLAYMATE_BREEDENG_AREA,
    PLAYMATE_DARK_AREA,
    PLAYMATE_HAND
]

API = "https://digimoncard.io/"